sudo: false

language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps

script:
  - make all
