################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps help

################################################################################

all: redis-latency-monitor ## Build all binaries

redis-latency-monitor: ## Build redis-latency-monitor binary
	go build redis-latency-monitor.go

install: ## Install binaries
	cp redis-latency-monitor /usr/bin/redis-latency-monitor

uninstall: ## Uninstall binaries
	rm -f /usr/bin/redis-latency-monitor

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

clean: ## Remove generated files
	rm -f redis-latency-monitor

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
