################################################################################

# This Makefile generated by GoMakeGen 0.6.1 using next command:
# gomakegen .

################################################################################

.PHONY = fmt all clean deps

################################################################################

all: redis-latency-monitor

redis-latency-monitor:
	go build redis-latency-monitor.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f redis-latency-monitor

################################################################################
